name = "anlysis3"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Anlysis3"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Anlysis3"
